### ISSUE TITLE
Unable to start docker compose demo server

### ISSUE THREAD

**Issue by unkcpz** [eth-cscs/firecrest#136]
I run into the following exceptions when try to start the demo deployment with docker composer:

```
fckeycloak         | 12:54:04,261 INFO  [org.wildfly.extension.microprofile.config.smallrye._private] (ServerService Thread Pool -- 48) WFLYCONF0001: Activating WildFly MicroProfile Config Subsystem                                     
fckeycloak         | 12:54:04,277 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 57) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments runnin
g multiple servers. Please make sure the attribute value is unique.                                                                                                                                                                        
fckeycloak         | 12:54:04,281 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 55) WFLYSEC0002: Activating Security Subsystem                                                                                               
fckeycloak         | 12:54:04,282 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service org.wildfly.security.security-event-listener.local-audit: org.jboss.msc.service.StartException in service 
org.wildfly.security.security-event-listener.local-audit: WFLYELY00004: Unable to start the service.                                                                                                                                       
fckeycloak         |    at org.wildfly.extension.elytron@10.0.3.Final//org.wildfly.extension.elytron.AuditResourceDefinitions$1$1.get(AuditResourceDefinitions.java:249)                                                                   
fckeycloak         |    at org.wildfly.extension.elytron@10.0.3.Final//org.wildfly.extension.elytron.AuditResourceDefinitions$1$1.get(AuditResourceDefinitions.java:231)     
```

and

```
fckeycloak         | 12:54:14,579 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 65) RESTEASY002220: Adding singleton resource org.keycloak.services.resources.WelcomeResource from Application class org.key
cloak.services.resources.KeycloakApplication                                                                                                                                                                                               
fckeycloak         | 12:54:14,652 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 65) WFLYUT0021: Registered web context: '/auth' for server 'default-server'
fckeycloak         | 12:54:14,673 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
fckeycloak         |     ("subsystem" => "elytron"),
fckeycloak         |     ("file-audit-log" => "local-audit")
fckeycloak         | ]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.security.security-event-listener.local-audit" => "WFLYELY00004: Unable to start the service.
fckeycloak         |     Caused by: java.io.FileNotFoundException: /opt/jboss/keycloak/standalone/log/audit.log (Permission denied)"}}
fckeycloak         | 12:54:14,790 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 46) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
fckeycloak         | 12:54:14,791 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
fckeycloak         | WFLYCTL0186:   Services which failed to start:      service org.wildfly.security.security-event-listener.local-audit: WFLYELY00004: Unable to start the service.
fckeycloak         | 
fckeycloak         | 12:54:14,834 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
fckeycloak         | 12:54:14,837 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
fckeycloak         | 12:54:14,837 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
fckeycloak         | 12:54:14,837 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: Keycloak 9.0.2 (WildFly Core 10.0.3.Final) started (with errors) in 13122ms - Started 682 of 988 services (1 services failed or missing depend
encies, 701 services are lazy, passive or on-demand)
```

**Comment by unkcpz** [comment]
As we discussed in the meeting since I only need a single user to communicate to the HPC, can you tell me which services are able to be discarded in the `docker-compose.yml`?

Best,
Jusong Yu

**Comment by aledabin** [comment]
Hello @unkcpz
The latest release fixes these problems, please try it and let us know.

**Comment by unkcpz** [comment]
@aledabin thanks a lot! I get it a run and all works well! 
I will then discuss with partners from the project to see how we processing the deployment and keep you posted.
