### ISSUE TITLE
Unable to start demo deployment due to demo_client failure

### ISSUE THREAD

**Issue by Fronox** [eth-cscs/firecrest#137]
Dear ETH CSCS Team,

I have attempted to run a demo deployment of FirecREST. Firstly, I got an error during the building of Docker images:
```bash
> docker compose build
...
=> ERROR [demo_compute internal] load metadata for docker.io/library/f7t-base:latest                                                         2.0s
 => [demo_client internal] load metadata for docker.io/library/python:3.7-alpine                                                              0.6s
 => [f7t-base internal] load metadata for docker.io/library/centos:7                                                                          0.0s
 => [demo_cluster internal] load build context                                                                                                0.0s
 => => transferring context: 36.65kB                                                                                                          0.0s
 => [f7t-base  1/47] FROM docker.io/library/centos:7                                                                                          0.0s
 => CANCELED [demo_cluster  2/47] RUN set -ex     && yum makecache fast     && yum -y install epel-release     && yum -y install        bzip  2.2s
 => [f7t-base internal] load build context                                                                                                    0.0s
 => => transferring context: 153B                                                                                                             0.0s
 => CANCELED [f7t-base 2/7] RUN yum install -y epel-release                                                                                   2.2s
 => [auth] library/f7t-base:pull token for registry-1.docker.io                                                                               0.0s
 => CANCELED [demo_client 1/4] FROM docker.io/library/python:3.7-
...
<Layers downloading>
...
 => [demo_client internal] load build context                                                                                                 0.1s
 => => transferring context: 314.58kB                                                                                                         0.1s
------
 > [demo_compute internal] load metadata for docker.io/library/f7t-base:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

This has been simply solved by the following command:

```bash
docker build -f deploy/docker/base/Dockerfile . -t f7t-base 
```

After that, I have started the deployment using `docker compose up -d` command. All of the services have successfully started except the `client`, which failed with error code 1:

```bash
> docker compose logs client
client  | Traceback (most recent call last):
client  |   File "firecrest_demo.py", line 17, in <module>
client  |     from flask_oidc import OpenIDConnect
client  |   File "/usr/local/lib/python3.7/site-packages/flask_oidc/__init__.py", line 41, in <module>
client  |     from itsdangerous import JSONWebSignatureSerializer, BadSignature, \
client  | ImportError: cannot import name 'JSONWebSignatureSerializer' from 'itsdangerous' (/usr/local/lib/python3.7/site-packages/itsdangerous/__init__.py)
```

Do you have any idea how to fix this issue?

Thank you in advance!

**Comment by aledabin** [comment]
Hello @Fronox,
Thank you very much for your report and proposed solution, please try the latest release which fixes this and other issues.
